- src/main/java/com/labsynch/labseer/service/ContainerServiceImpl.java
Fixed mistake in Oracle recursive SQL that was pulling "parent" node's type and kind instead of "child" node. Bug was not present in Postgres query.
> Added catch for withContainers being null. Fixes #125.

- src/main/java/com/labsynch/labseer/api/ApiLsThingController.java
- src/main/java/com/labsynch/labseer/service/LsThingService.java
- src/main/java/com/labsynch/labseer/service/LsThingServiceImpl.java
This is an additional commit I made on the generic thing search branch addition from last week.
It adds an optional lsKind parmeter to the generic search route.
> fixes mcneilco/acas#696 add optional ls kind parameter to generic thing search

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
The "_registered.csv" file already had a warning columns for when numeric values, and dates were being coerced.  This just adds a "trim" to string values and warns the users if the value changed in the process.
Users will see warnings like this:
And the "_registered.csv" file will look like this:
> fixes mcneilco/acas#712 trim string values from sdf input files

- src/main/java/com/labsynch/labseer/service/LsThingServiceImpl.java
Currently if a numericValue is used in advanced search, the code will fail if the search value cannot be coerced to numeric.
E.g.  'asdf'
This code change will return a negative condition `criteriaBuilder.disjunction()` to return a false for the value being searched on for this field,  this does not affect other parts of the query where there may be a match. See `0=1` in the sql produced below
```sql
select distinct lsthing0_.id as col_0_0_
from ls_thing lsthing0_
inner join ls_thing_state lsstates1_ on lsthing0_.id=lsstates1_.lsthing_id
inner join ls_thing_value lsvalues2_ on lsstates1_.id=lsvalues2_.lsthing_state_id
inner join ls_thing_state lsstates3_ on lsthing0_.id=lsstates3_.lsthing_id
inner join ls_thing_value lsvalues4_ on lsstates3_.id=lsvalues4_.lsthing_state_id
inner join …
```
> fixes mcneilco/acas#720 Ls thing advanced search of character string on a numericValue field

- Dockerfile
I tested running the OpenSSL and keytool import command on a server which used self signed certs.
fixes #260
See pull request https://github.com/mcneilco/tomcat-maven/pull/1
> Update to new tomcat image which has openssl and cacerts permissions for runner

- src/main/java/com/labsynch/labseer/chemclasses/indigo/CmpdRegMoleculeIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/CmpdRegMoleculeJChemImpl.java
These are additionally changes I missed for the other chemistry packages.  These are required methods on CmpdRegMolecule.
> Fixing jchem and indigo builds

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
Fixes #291
When compound inventory is turned on, if amount, or amount units or barcode are provided and any of the other 2 are not, then throw an error that the other 2 are required.
Fixes #291
Bulk loaded a file, mapped barcode and amount but not amount units.  Got an error that said "Lot Amount Units required".
I tested with the two other combinations as well as not providing any inventory information.
> CmpdReg bulkloader should require amount amount units and barcode when any one of them is provided

- Dockerfile
- Dockerfile-bbchem
- Dockerfile-indigo
- Dockerfile-jchem
- Dockerfile-multistage
Removed chown statement as it was unnecessary and caused issues when using docker build without docker build kit
Added "/" to the end of copy step of acas to fix and issue when building without docker build kit
Fixes #293
I tested a non docker build kit build of the Jchem version and verified the server came up and ran
I tested a docker build kit build of the bbchem version and verified the server came up and ran
> Docker build roo throws unable to convert uid/gid chown string to host mapping

- src/main/java/com/labsynch/labseer/exceptions/NonUniqueAliasException.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentAliasService.java
- src/main/java/com/labsynch/labseer/service/ParentAliasServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentService.java
- src/main/java/com/labsynch/labseer/service/ParentServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/PropertiesUtilService.java
- src/main/java/com/labsynch/labseer/utils/PropertiesUtilServiceImpl.java
Add config `server.service.external.preferred.batchid.allowParentAliasLotNames`
Checks uniqueness of parent aliases globally on the system
Fixes #324
Bulkloader with this setting on and trying to load duplicates:
Turned off validation and verified mode and verified its still caught:
Verified that "Within the file" duplicate checking works:
Single reg:
I also verified this properly ignores soft deleted ( "ignored" and "deleted" aliases)
> Make CReg enforce globally unique parent aliases

- src/main/java/com/labsynch/labseer/db/migration/postgres/V2_3_0_8__update_stereo_category_defaults.java
This is a flyway migration to change the stereo categories on a system which has no parents (i.e. a new system).
The new categories are:
- No stereochemistry
- Single stereoisomer
- Single stereoisomer - arbitrary assign
- Single stereoisomer - partial assign
- Mixture
- Mixture - arbitrary assign
- Mixture - partial assign
- Relative mixture
- Relative mixture - arbitrary assign
- Unknown
ACAS-89
- Updated an existing system and confirmed stereo categories were unchanged by checking the table and verified this log line was printed:
```
roo_1        | 11 May 2022 20:04:37 3013 [main] INFO  com.labsynch.labseer.db.migration.postgres.V2_3_0_8__update_stereo_category_defaults [] - Not updating stereo category defaults because there are already rows in the parent table
```
- Created a fresh …
> Update default stereo categories on new systems

- src/main/java/com/labsynch/labseer/api/ApiPhysicalStateController.java
- src/main/java/com/labsynch/labseer/api/ApiStereoCategoryController.java
- src/main/java/com/labsynch/labseer/api/ApiVendorController.java
- src/main/java/com/labsynch/labseer/domain/PhysicalState.java
- src/main/java/com/labsynch/labseer/domain/StereoCategory.java
- src/main/java/com/labsynch/labseer/domain/Vendor.java
- src/main/java/com/labsynch/labseer/dto/BulkLoadPropertiesDTO.java
- src/main/java/com/labsynch/labseer/dto/BulkLoadPropertyMappingDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- Add ignoreCase lookups for vendor, physical state, stereo category
- I wasn't totally sure how far to take this. There are some lesser-used categorical lookups that this could be extended to, like Parent Annotation
Ran acasclient tests including new one for wrong-case inputs: https://github.com/mcneilco/acasclient/pull/55
> ACAS-98: Make SDF bulk loader case insensitive

- src/main/java/com/labsynch/labseer/dto/BulkLoadRegisterSDFResponseDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
Add bulk load file `id` to the output of bulk load reg responses
ACAS-311
ACAS-273
Wrote ACAS client tests for ACAS-273 and changed the behavior of the purge bulk load test to use the `id` as a handle when bulk loading and then purging a file.
> Return bulk load file id

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
Minor code changes...
[ACAS-99](https://jira.schrodinger.com/browse/ACAS-99): CReg combines salts from structure and sdf prop; should fail and warn user instead
[ACAS-40](https://jira.schrodinger.com/browse/ACAS-40): CReg bulk loader should warn when assigning existing compound structure a new ID
> Dale minor fixes sprint9

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureService.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
Processor does its own standardization of the molecule and if you don't pass standardization configs, it will apply a default standardization before doing hashing.  In this PR, I removed the call to preprocessor as the output was being thrown out anyway and instead just call the process route and include the configured standardization rules.
ACAS-339
Ran dry run standardization on a test server and verified the dry run structure looks like structure returned from calling the preprocessor via command line using the same mol and processor configs.
> ACAS w/BBChem not producing standardized structures

- src/main/java/com/labsynch/labseer/api/ApiAnalysisGroupValueController.java
- src/main/java/com/labsynch/labseer/api/ApiExportController.java
- src/main/java/com/labsynch/labseer/api/ApiMetalotController.java
- src/main/java/com/labsynch/labseer/domain/AnalysisGroupValue.java
- src/main/java/com/labsynch/labseer/dto/AnalysisGroupValueDTO.java
- src/main/java/com/labsynch/labseer/dto/CmpdRegBatchCodeDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ContainerService.java
- src/main/java/com/labsynch/labseer/service/ContainerServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ExperimentService.java
- src/main/java/com/labsynch/labseer/service/ExperimentServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ExportService.java
- src/main/java/com/labsynch/labseer/service/ExportServiceImpl.java
- src/main/java/com/labsynch/labseer/service/LotService.java
- src/main/java/com/labsynch/labseer/service/LotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentLotService.java
- src/main/java/com/labsynch/labseer/service/ParentLotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentService.java
- src/main/java/com/labsynch/labseer/service/ParentServiceImpl.java
- src/main/java/com/labsynch/labseer/service/SaltFormService.java
- src/main/java/com/labsynch/labseer/service/SaltFormServiceImpl.java
- Added service to delete a lot including dependencies:
- If remaining is orphan salt form/iso salts then delete it
- If remaining is orphan parent then delete it
- Experiment analysis groups
- Containers
- Added some functionality around dependency checking
- Route to export to SDF via output stream rather than json with string file
ACAS-49
Ran acas client tests
> Delete lot ACAS-49

- src/main/java/com/labsynch/labseer/api/ApiParentController.java
- src/main/java/com/labsynch/labseer/dto/ParentSwapStructuresDTO.java
- src/main/java/com/labsynch/labseer/dto/ParentValidationDTO.java
- src/main/java/com/labsynch/labseer/service/ParentSwapStructuresService.java
- src/main/java/com/labsynch/labseer/service/ParentSwapStructuresServiceImpl.java
Create the service to swap two parent structures. Swapping of structures is only allowed if the two parent structures are unique or just duplicates of each other than the swapping.
Recommended workflow to check:
1. ParentSwapStructuresDTO > ParentSwapStructures
2.  APIParentController > swapParentStructures
3. ParentSwapStructureServiceImpl > swapParentStructurs.
[ACAS-286](https://jira.schrodinger.com/browse/ACAS-286).
See testing section in the acas PR.
~I am seeing issues when querying duplicate parents i.e in the cases where duplicate parents do exist(confirmed via the `/validateParent` API). I am not getting the duplicate parents listed in the `swapParentStructures` service.~
> Add service to swap two parent structures.

- src/main/java/com/labsynch/labseer/api/ApiParentLotController.java
- src/main/java/com/labsynch/labseer/domain/AnalysisGroupValue.java
- src/main/java/com/labsynch/labseer/domain/ContainerValue.java
- src/main/java/com/labsynch/labseer/domain/ExperimentValue.java
- src/main/java/com/labsynch/labseer/domain/ProtocolValue.java
- src/main/java/com/labsynch/labseer/domain/SubjectValue.java
- src/main/java/com/labsynch/labseer/domain/TreatmentGroupValue.java
- src/main/java/com/labsynch/labseer/dto/CmpdRegBatchCodeDTO.java
- src/main/java/com/labsynch/labseer/dto/ReparentLotResponseDTO.java
- src/main/java/com/labsynch/labseer/exceptions/DupeLotException.java
- src/main/java/com/labsynch/labseer/service/AnalysisGroupService.java
- src/main/java/com/labsynch/labseer/service/AnalysisGroupServiceImpl.java
- src/main/java/com/labsynch/labseer/service/AssayService.java
- src/main/java/com/labsynch/labseer/service/AssayServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ContainerService.java
- src/main/java/com/labsynch/labseer/service/ContainerServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ExperimentService.java
- src/main/java/com/labsynch/labseer/service/ExperimentServiceImpl.java
- src/main/java/com/labsynch/labseer/service/LotService.java
- src/main/java/com/labsynch/labseer/service/LotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentLotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ProtocolService.java
- src/main/java/com/labsynch/labseer/service/ProtocolServiceImpl.java
- src/main/java/com/labsynch/labseer/service/SaltFormServiceImpl.java
- src/main/java/com/labsynch/labseer/service/SubjectService.java
- src/main/java/com/labsynch/labseer/service/SubjectServiceImpl.java
- src/main/java/com/labsynch/labseer/service/TreatmentGroupService.java
- src/main/java/com/labsynch/labseer/service/TreatmentGroupServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/PropertiesUtilService.java
- src/main/java/com/labsynch/labseer/utils/PropertiesUtilServiceImpl.java
Updated reparent lot routes to 
- return a structured output which contains
-  original parent corp name
-  original lot corp name
- original lot number
- the new lot as updated (or simulated via new dry run flag) 
- update experimental data
- renames codeType "codeValue" codeValue "batch code" values on subject, treatment, experiment and protocol levels
- deletes old parent if it is orphaned
- optional dry run mode which returns the expected output lot (including updated corp name and lot number)
ACAS-216
Ran acas client tests and tests described on acas node layer ACAS-216 pull request
> Reparent lot route updates ACAS-216-reparent-lot

- src/main/java/com/labsynch/labseer/domain/Lot.java
The old version of reparent lot did not catch when it was leaving behind parents with no salt_forms.  This has been fixed but we have systems which have this data state.  This fix allows standardization dry run and standardization to run successfully in this state.  It looks like we already had a check for if we were returning null but we weren't catching a no result exception.
ACAS-388
Ran the code on a system with the required error state (Parents with no salt forms).
> Catch no original structure found when running dry run standardization

- src/main/java/com/labsynch/labseer/service/ParentSwapStructuresServiceImpl.java
Parent structure swap route was not updating molecular weight, mol formula, lot molweights, or structure tables.
Switched to using existing parentStructureService.update method which does all this.
Added additional acasclient tests to confirm mol weight and mol formula changes. Confirmed those tests were broken before this change and fixed afterwards.
Structure table updates will need to be tested on a BBChem system since indigo does not use a separate structure table AFAIK.
> ACAS-403: Fix lack of molWeight updates when swapping structures

- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
Update `modifiedDate` field when editing a `Lot`.
When a `Lot` is edited, the `modifiedDate` field is not updated. We are copying the `modifiedDate` value from the existing lot which never has the `modifiedDate` value. Here we update the `modifiedDate` field to be current date.
[ACAS-364](https://jira.schrodinger.com/browse/ACAS-364).
TDD. Check [acasclient PR](https://github.com/mcneilco/acasclient/pull/87).
> Update modified date of the Lot.

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/domain/Lot.java
Backporting fixes for ACAS-388 (#348) and ACAS-370 (#346) to release/1.13.7
These fixes have been tested in release/2022.1.x. No additional testing is planned.
> ACAS-407: Backport critical kubernetes-relevant fixes to 1.13.7 release branch

- src/main/java/com/labsynch/labseer/service/StructureServiceImpl.java
Fixing an issue mentioned in https://github.com/mcneilco/acas/pull/1002
The V2000 reader cannot read V3000 MOL strings, whereas this implementation works for both V3000 and V2000 MOL strings.
Tested in local dev setup and confirmed both V3000 and V2000 inputs generated images successfully.
> ACAS-6: Switch to generic V3000/V2000 mol reader

- src/main/java/com/labsynch/labseer/api/ApiSaltController.java
- src/main/java/com/labsynch/labseer/api/ApiStructureImageController.java
- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
Add a new route to render a MOL string as base64-encoded PNG.
Also fixed a small grammar issue in duplicate messages.
Tested locally alongside changes from https://github.com/mcneilco/acas/pull/1002
> ACAS-6: Follow-up fix for image rendering

- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
**Reproduce/Test:**
As a CReg admin, navigate to the CmpdRed Salts panel, pick any salt from the table and edit the abbreviation or name.
Click the 'Next' button.
**Bug Results:**
Any changes cannot be saved since they are always referred to as duplicates of existing values, even though they are added as a part of the same workflow.
**Post-Fix Results:**
After reviewing the dependencies, the changes should be allowed to save. There should be no error/warning for the name OR abbreviation already existing in the system if the name OR abbreviation (respectively) of the active salt edit isn't changed.
> Hotfix - Editing Salt Treats No Change to Abbrev / Name As Duplicate in System 

- src/main/java/com/labsynch/labseer/api/ApiMetalotController.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- This is meant to fix a bug when CReg is configured to reject duplicate aliases and you try to register a new compound with a duplicate alias. Currently CReg will save the parent, then return a 500 server error. Locally the error gets rendered properly in the client, but gives the false impression that the parent wasn't registered. In typical LiveDesign deployment scenarios, the 500 error is trapped by nginx and the CReg client can't properly handle & display the cause of the error.
- Added a call to "validateParentAliases" within the MetaLot processAndSave route _before_ the parent is saved. Previously it only happened as part of "updateParentAliases" which happened after the parent was saved.
- Switched the error response of MetaLot from 500 to 400. Along the way I discovered that the …
> ACAS-400: Fix error flow for duplicate parent aliases

- src/main/java/com/labsynch/labseer/dto/BulkLoadParentSaltFormLotDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
We'd never optimized the performance of the checkPurgeFileDependencies route, and it was written very naively, with a lot of unnecessary and repeated fetching of data. Rewrote it to do a single DB query to pull back only the minimal relevant parent / saltForm / lot information as a flattened set of DTO objects, then loop through and build up the same data structures as before.
Tested locally both for performance and for correct behavior.
Performance for checking dependencies on a 999 lot file with minimal dependencies went from 2.5 minutes to < 1 s.
Confirmed that single registered lots are correctly caught and reported.
Ran ACASClient test that checks SEL file dependencies, and that test passed.
> ACAS-439: Performance rewrite of checkPurgeFileDependencies

- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
**Reproduction of Bug**
Edit a salt that is known to either have linked experiments or containers and proceed to update. You may choose to update the name, abbrev, or structure. 
**Bug Results:**
Though the dependency messages contain all the dependent experiments and/or containers, it is jarring and not human-readable.
**Post-Fix Results:**
Validation should contain warnings about the dependent experiments and/or containers that are easy to read and not overwhelming to the user.
> Cleanup Linked Experiment and Container Warning Message

- src/main/java/com/labsynch/labseer/service/LsThingService.java
Removed interface for LsThingService. getLsThingsByIds which has been replaced with LsThing.findLsThingsByIdsIn
ACAS-460
Ran builds of BBChem, Indigo and Jchem docker images
> Fix issue with missing implmentation by removing interface

- src/main/java/com/labsynch/labseer/api/ApiParentController.java
- src/main/java/com/labsynch/labseer/service/ParentSwapStructuresServiceImpl.java
**Issue:**
When `swapParentStructures` API is called via LiveDesign with an invalid corporate name or when there are validation errors or when swap is going to introduce duplicates the response incorrectly mentions that LiveDesign is restarting.
**Bug:**
In `swapParentStructures` API when the swap doesn't go through we set the response status code to `INTERNAL_SERVER_ERROR` which LiveDesign treats as "an internal error".
**Fix:**
We didn't actually have any internal errors on the server but the client gave bad inputs and so we now change the response status to be `BAD_REQUEST`.
[ACAS-430](https://jira.schrodinger.com/browse/ACAS-430)
Checked on an actual LiveDesign server that response json reaches the client.
Update acasclient logic and ran all acasclient tests.
> Update swapParentStructures to raise BAD_REQUEST for invalid user inputs.

- src/main/java/com/labsynch/labseer/domain/BulkLoadFile.java
- src/main/java/com/labsynch/labseer/dto/BulkLoadRegisterSDFRequestDTO.java
- src/main/java/com/labsynch/labseer/dto/PurgeFileResponseDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/resources/db/migration/postgres/V2.4.0.1__bulk_load_file_original_name.sql
ACAS introduces spaces and numbers in parentheses to keep SDF and zip filenames distinct because it drops them all into a common privateUploads folder. This makes life harder for users who may upload the same file multiple times but get different filenames when they re-download that same file from ACAS, or when they download derived zipfiles.
This acas-roo-server change adds an "originalFileName" column to bulk_load_file to track the original file name, and passes it back to the node layer for rendering.
Local testing of uploading the same file many times. Confirmed that the validation download zip, its contents, the registration download zip, and all the links on the purge files page (including the link / summary after purging) all show the original filename, and all download the correct …
> ACAS-271: Preserve file naming in SDF bulk loader

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- Ignored aliases were breaking our duplicate alias detection.  This skips aliases which are ignored or deleted from that validation.
ACAS-477
Registered a compound with an alias of BLAH and then deleted that alias via the GUI which sets it to ignored in the database
Bulk loaded another lot of the same compound and verified that I got the same erroneous error `Within File, Parent Alias BLAH is not unique`
Applied my fix and the error went away
> Need to skip ignroed and deleted aliases when checking for duplicates on the parent during bulk load registration

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Refactor fill missing structures by adding fillMissingParentStructuresByParentIDList and switching transactional block to be on the new function
ACAS-476
Ran fill missing structures on a server with 1.7 million compounds and the memory never went over 3 Gb
> ACAS-476-fill-missing-structure-memory

- src/main/java/com/labsynch/labseer/domain/DryRunCompound.java
- src/main/java/com/labsynch/labseer/domain/Parent.java
- src/main/java/com/labsynch/labseer/domain/StandardizationDryRunCompound.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/Request.java
- src/main/resources/db/migration/postgres/V2.4.0.2__standardization_dry_run_indexes.sql
- Pushes duplicate checking logic into the database for Standardization to speed up cases where there are many structure duplicates on the system that differ by stereo category and stereo comment.
ACAS-481
Ran standardization dry run on a large scale system and times improved drastically from an unknown time (because it took to long to even give a time to 10871.80/rows per minute).
> ACAS-481: Standardization duplicate checking to refactor for speed optimization

- src/main/java/com/labsynch/labseer/domain/Lot.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Replaced function `getOriginallyDrawnAsStructure(Parent parent)` with`getOriginallyDrawnAsStructuresByParentIds(List<Long> parentIds)` to speed up standardization
- The logic is the same.  Select min lot number with an as drawn structure and use that as the as drawn structure of the parent.
ACAS-483
Ran a dry run standardization and it sped up the run from `802.86 average speed (rows/min)` to `9916.62 average speed (rows/min)`
> ACAS-481: Get as drawn structure in batch to speed up standardiation

- src/main/java/com/labsynch/labseer/chemclasses/CmpdRegSDFWriter.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureService.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegSDFWriterBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/indigo/CmpdRegSDFWriterIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/CmpdRegSDFWriterJChemImpl.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Add `writeMols(List<CmpdRegMolecule> cmpdRegMoleculeList)`
- This speeds up some implementations which are faster writing to SDF in bulk than one at a time
- Fixed a bug that we weren't closing the file which is required to fully flush the file writer. Without this change we could intermittently loose a few mols in the output file.
ACAS-488
Tested by downloading 18K compounds which takes about 1 minute with this new code
> ACAS-488: Write list of mols to SDF

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Fill missing salt structure representation on startup rather than on standardization
- Allow duplicate salt structures instead of skipping over duplicates when filling in missing structures (in rare cases some system may have duplicate salt structures and this process shouldn't fix that).
- 
ACAS-496
Ran the following sql to create a salt duplicate:
```
insert into salt (select nextval('hibernate_sequence'), abbrev, 0, formula, false, mol_structure, mol_weight, 'test', original_structure, 0, charge from salt limit 1);
```
With the original code, verified that restarting ACAS did not fill in the salt structure and printed that it was a duplicate salt.
With the new code, varied that the correct row was created in bbchem_salt_structure and the cd_id of the salt was updated to match the new …
> ACAS-496: Fill missing salt structure representations on start, allow duplicates.

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- src/main/resources/db/migration/bbchem/postgres/V2.4.0.4__bbchem_fill_missing_structures_fix.sql
**Steps to Reproduce**: 
- On a system with ACAS w/BBChem register a compound with the UI (not bulk loader).
- Restart ACAS
- Once acas is up, do a database search for the salt_form like:
- select * from salt_form where corp_name = 'CMPD-0000003';
**Expected Results:**
The salt_form.cd_id should be 0
**Actual Results:**
The salt_form.cd_id is set to a number
**Extra Information:**
ACAS runs a process on startup looking for structures that are filled in but are missing a chemical representation in the corresponding structure table (in this case that table is bbchem_salt_form_structure). The code is not ignoring mol_structures which are set to "" and trying to register them.
This isn't causing any obvious problems in the database but its unnecessary work and causes some confusion. If a …
> ACAS-494: Fill missing structure ignore empty mols

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- Fix issue with calling the wrong method and not actually updating salt_form structures
- Fix comment which referenced parents instead of salt_forms
ACAS-495
Truncated a bbchem_salt_form_structure table and restarted ACAS
Verified bbchem_salt_form_structure was re populated with all structures from salt_form where mol_structure was not empty.
Verified that salt_form.cd_ids were update with corresponding new entries.
> ACAS-495: Fix salt_form fill structures

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegSDFWriterBBChemImpl.java
- This change is a fix for the in-memory / file-less SDF writer in the BBChem implementation. It is used by the SaltService to produce an SDF when users download all salts.
- Prior implementation returned a string like `java.io.FileWriter@490b189e`
- This fixes it to use a StringWriter whose "toString" method works as intended and returns all the text that has been written to the writer.
Tested on frost-acas-quickstart.dev.bb.schrodinger.com by tagging `ACAS-473-dev1` from my dev branch, and deploying the tag onto that server which uses bbchem.
Confirmed the issue before updating roo, and confirmed it produces a proper SDF after this change.
> ACAS-473: Fix BBChem in-memory SDF writer

- src/main/java/com/labsynch/labseer/service/ExportServiceImpl.java
- Use new `writeMols(List<CmpdRegMolecule> cmpdRegMoleculeList)` in `ExportServiceImpl` `writeLotsToSDF(String exportSDFFileName, Collection<LotDTO> lotDTOs)` to speed up download of `Current File` SDF in CmpdReg bulk loader.
ACAS-471
Clicked download on a data set and verified the results downloaded much faster on a BBChem implementation server.  Checked the results and verified that the number of lots matched the expected output.
> ACAS-471: bulk export

- src/main/java/com/labsynch/labseer/domain/Lot.java
- src/main/java/com/labsynch/labseer/service/LotServiceImpl.java
- Use max auto lot number if set to select lot numbers < or equal to the max auto lot number when getting the next lot number during bulk reg and reparent lot
- Previously reparent lot paid attention to maxAutolot number only for the purposes of keeping a lot number if it was above the max auto lot number, however if the target parent had a lot greater than the max auto auto lot number it would still grab this large lot number and add 1 to it.
ACAS-502
Loaded a compound with lot number 1
Added a lot manually with lot number 1001
Bulk loaded another lot and verified the lot number assigned was lot 2
Reparented a lot onto a parent that had a lot number of 1001 and verified it was assigned lot 3 (lowest lot number below the max auto lot number)
> ACAS-502: Max auto lot number for bulk loader

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- Fixing issues with URL refactor
ACAS-387
Placed debugger in each BBChemStructureService URL and verified each one worked.
Path | Worked
-- | --
private final String CONVERTER_PATH = "/converter/api/v0/convert/"; | 1
private final String EXPORTSDF_PATH = "/sdf_export/api/v0/"; | 1
private final String FINGERPRINT_PATH = "/fingerprint/api/v0/"; | 1
private final String IMAGE_PATH = "/image/api/v0/"; | 1
private final String PARSESDF_PATH = "/parse/api/v0/"; | 1
private final String PROCESS_PATH = "/preprocessor/api/v0/process/"; | 1
private final String SPLIT_PATH = "/split/api/v0/"; | 1
private final String SUBSTRUCTURE_PATH = "/substructure/api/v0/"; | 1
private final String CONFIG_CHECK_PATH = "/preprocessor/api/v0/config/check/"; | 1 …
> Acas 387 url fix

- src/main/java/com/labsynch/labseer/api/ApiFileSaveController.java
- src/main/java/com/labsynch/labseer/domain/FileList.java
- src/main/java/com/labsynch/labseer/dto/FileSaveReturnDTO.java
- src/main/java/com/labsynch/labseer/dto/FileSaveSendDTO.java
- src/main/resources/db/migration/postgres/V2.4.0.6__file_add_writeup_column.sql
ACAS-498 adds a new "Writeup" text field associated with each analytical file attached to a Lot in CReg. The purpose of this is to store standard NMR and LCMS writeup information (https://pubsapp.acs.org/paragonplus/submission/acs_nmr_guidelines.pdf) used in publications, alongside the corresponding pdfs and raw data.
The portion in this PR adds a new "writeup" TEXT type column to the `file_list` table, and plumbs that new field through the FileList domain class and a few DTO classes, and through the API method used when saving analytical files.
Tested locally that I can upload and save an analytical file with a writeup. Confirmed that it's rendered properly when the page is reloaded after save.
> ACAS-498 Add writeup TEXT column to FileList

- Dockerfile-multistage
- src/main/java/com/labsynch/labseer/chemclasses/CmpdRegSDFReader.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureService.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegSDFReaderBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegSDFWriterBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/indigo/ChemStructureServiceIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/indigo/CmpdRegSDFReaderIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/ChemStructureServiceJChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/CmpdRegSDFReaderJChemImpl.java
- src/main/java/com/labsynch/labseer/domain/Parent.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ChemStructureService.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
@brianbolt I'm still doing more testing and thinking more about this, but I think I have the "first draft". I'd like a review from you to see if there are major things I've missed, bugs you can spot, or better ideas you have based on what I've done so far.
- The basic observation here is that calling BBChem many times with small payloads is slow, and calling it few times with large payloads is fast. Thus the changes here try to take as many points where we call BBChem, and front-load them to doing calls in bulk.
- Read incoming SDF in large batches - during file / property scanning, property validation, and the dryrun/non-dryrun `registerSDF`.
- Call "standardize" i.e. "process" upfront and store the resulting CmpdRegMolecule as a transient property on the parent, pulling it out when …
> ACAS-504: Improve BBChem bulk SDF upload performance

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegSDFWriterBBChemImpl.java
I noticed in my testing after merging ACAS-504 that the "Download All Salts SDF" button in Salt Browser was writing the same salt out 3 times to the SDF. I traced it back to the fact that the code calls "close()" then calls "getBufferString" twice. This should be safe to do, so I fixed my modifications to CmpdRegSDFWriterBBChemImpl to clear out the molCache whenever "close" or "getBufferString" is called, so it's safe to call multiple times.
Tested locally that after this fix, the Salts SDF only had one entry per Salt.
> ACAS-504 Followup: Fix for writing SDF

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
**Steps to Reproduce**
Bulk load a new structure with a Parent Alias mapped in. This creates a new parent with the alias, and a new lot.
Then load the same structure with a different Parent Alias value. This will create a new lot on the existing parent.
**Bug Behavior**
A new lot is created, but the alias from the second upload is ignored. The parent ends up with one alias (only the one from the first upload).
**Fixed Behavior**
A new lot will be created and the existing parent will be updated to add the new Parent Alias value. The parent will end up with two aliases (one from each upload)
**Example**
One of the tests I conducted was to have one compound with the alias "Dale's Favorite Compound" and I uploaded the same structure with the alias of "Second Alias". The result was two lots …
> Fixed: Alias dropped when new lot of compound gets registered in bulk loader

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- Bug occurs when loading a structure which has already been registered
- Root cause is that the `validateParent` function overwrites the `parent` variable with a `foundParent` from the database if it finds a match, and the `foundParent` doesn't have the new transient `cmpdRegMolecule` variable filled in with the standardized CmpdRegMolecule.
@dalejerikson and I looked at this together, and came up with three possible styles of fixes:
1. Add more "if cmpdRegMolecule is null" checks, and re-standardize the structure if we've lost the standardizedMolecule
2. Grab the standardized molecule from `parent` before it gets overwritten, then pop that same value back into the new `parent` that came from the database.
3. When we find a match (`foundParent`), hydrate the standardized CmpdRegMolecule …
> ACAS-504 followup: Fix NullPointerException when loading a second lot of the same compound

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ParentAliasService.java
- src/main/java/com/labsynch/labseer/service/ParentAliasServiceImpl.java
- Bug was that trying to load the same alias onto an existing parent would yield a duplicate alias error, rather than being a no-op
- Fix is to pass in the parent ID for the parent whose aliases are being validated, and skip reporting duplicates if the duplicate alias was found on the same parent
Ran acasclient tests locally with config `client.cmpdreg.metaLot.allowDuplicateParentAliases=false`
Confirmed that @dalejerikson 's `test_051_bulk_load_update_parent_alias` now passes
One other test fails with this config: `test_005_swap_parent_structures`, but that is expected because that case intentionally registers a duplicate alias to test an error thrown when an alias is ambiguous.
> ACAS-523: Skip throwing duplicate alias error if dupe is on the same parent

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
Fixed ACASClient tests (https://github.com/mcneilco/acasclient/pull/101) enough to uncover two more bugs:
```
>  <Parent Alias>
Fourth Alias; Fifth Alias; Sixth Alias; Seventh Alias;
```
parsed as (note leading whitespace):
```
["Fourth Alias"," Fifth Alias"," Sixth Alias"," Seventh Alias"]
```
After fixing the above issue, noticed test was still failing. `compareParentAliases` function seems correct, but `updateParentAliases` function was not producing correct results, leading to duplicate aliases getting created.
The logical flow inside that function was confusing  enough that I rewrote it to be able to result in the correct behavior.
Ran acasclient tests locally and confirmed this fixes the test failures on test_051 mentioned here https://github.com/mcneilco/acasclient/pull/101
> ACAS-489 Followup: Bug fixes for whitespace and for alias set comparisons

- src/main/java/com/labsynch/labseer/domain/DryRunCompound.java
- src/main/java/com/labsynch/labseer/domain/StandardizationDryRunCompound.java
- src/main/java/com/labsynch/labseer/service/ParentServiceImpl.java
- Delete standardization dry run compound when deleting a parent compound
ACAS-526
- Test locally to reproduce
- Ran acas client test with breakpoint to register an SDF file (then stopped the run so teardown was run)
- Executed standardization dry run
- Tried to delete one of the lots (single lot on parent so the parent is also attempted to be deleted)
- Result was failure to delete lot
- Test fix
-  updated the code, ran the same test and now the parent is deleted successfully (including from standardization dry run table)
> ACAS-526: Delete standardization dry run compound when deleting a parent compound

- src/main/resources/db/migration/postgres/V2.4.1.0__data_column_order_states.sql
- Earlier PR #394 was merged but caused issues and was reverted
- Primary issue was that it failed on brand new / empty systems due to some missing sequences that are created when ACAS starts up and runs setup routes
- Fixed this issue by wrapping the entire script in a "DO" block and thus turning it into an anonymous pl/pgsql function. This allows us to return early if no experiment data exists.
- While locally testing upgrade from 2022.4.x to this branch, found a few more breaking issues and fixed them. They were missing ddict types and kinds, a copy/paste typo where column name was put in instead of units, and some followthrough on switching to pl/pgsql (replacing lone "select" statements with "perform")
I'm sorry this is displaying as one big change, but you can look through the …
> ACAS-413: DB migration for endpoint management (2nd attempt)

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- Some bbchem endpoints seem to have stopped accepting trailing slashes
- Tested each endpoint on my 2023.1.x k8s dev environment, and changed the ones that no longer work
- Has not yet been tested through Roo, but I've checked the edited endpoints. Will confirm this in k8s after it builds & pushes
> ACAS-564: fix bbchem urls that no longer tolerate trailing slash

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- SDF with some Parent Aliases populated, others blank, and others missing that property entirely were failing to register when `allowDuplicateParentAliases` was set to false.
- Root issue seems to be we were passing through empty-string aliases and trying to create them
- Fixed it by filtering out empty strings and nulls after the string is split and trimmed
- Also removed some misleading logging
- Reproduced the issue locally and tested with several combinations of files, and with combinations of:
- registering new compounds
- registering new lots of existing compounds with & without aliases
- added acasclient test
> ACAS-567: Trim empty strings in incoming aliases

- src/main/resources/db/migration/postgres/V2.4.1.1__missing_column_ddict_values.sql
- Testing showed that some "Dose Response" columns (Slope, Min, Max) present in SEL files were being saved in Experiment "data column order" states by SEL, but the necessary DDict values to display their column names in the Protocol Endpoint Manager GUI were not getting created
- Simplest fix is to add a new migration that looks for any missing ddict values and adds them
Tested locally by:
- Starting up ACAS on release/2022.4.x
- Loading a Dose Response Experiment
- Switching ACAS to release/2023.1.x and starting up, which applies the previous migration V2.4.1.0
- Logging in, navigating to Protocol Browser and confirming there are endpoints whose names are not displaying
- Switch Roo image to locally-built one with these changes, start up, which applies the new migration V2.4.1.1
- Login …
> ACAS-413: Add a new migration to catch any "missed" ddict values.

- src/main/java/com/labsynch/labseer/service/ExperimentServiceImpl.java
Search the project field when doing a query terms search (experiment browser)
ACAS-575
Ran acasclient tests
> ACAS-575: Search experiment project in experiment browser search

- src/main/java/com/labsynch/labseer/api/ApiExperimentController.java
- src/main/java/com/labsynch/labseer/service/ExperimentService.java
- src/main/java/com/labsynch/labseer/service/ExperimentServiceImpl.java
- src/main/resources/db/migration/postgres/V2.4.2.0__overwritten_experiment_status.sql
- src/test/java/com/labsynch/labseer/service/ExperimentServiceTests.java
Users often are hampered by apparent 'missing data' when a registrar fails to update the experiment name field. A new experiment code is generated and the previous ACAS file-data is replaced (overwritten). In most cases, the current behavior is desired, since it allows trivial adjustments to units, endpoint labels, etc. But in wrong hands it leads to a confusing state. Moreover, as registrars it is difficult to even discover such cases and troubleshoot. Here we want to enhance the Experiment Browser table such that it can be used to recover from such registration failures.
**Scope of This Work**
- Backend Work Supporting the Adding of "Overwritten" as an "Experiment Status"
- Adding a route in the delete experiment logic that changes the status field
- DB migration to change the …
> Improve Reporting of Overwritten Experiments and Migration of Old Experiment Statuses to "Overwritten"

- src/main/java/com/labsynch/labseer/domain/Lot.java
Catch case when there are no lots below maxAutoLotNumber and return 0…… as the max Lot Number. This prevents upstream NullPointerExceptions.
- The scenario for this bug is when a user is trying to reparent a lot (i.e. lot 1) of a Parent A onto another Parent B which only has a huge lot number (i.e. lot 4000). When the `maxAutoLotNumber` config is set (i.e. to 1000) the expected behavior is that Parent A Lot 1 will become Parent B Lot 1.
- On ACAS 2022.1.0 the actual behavior is that Parent A Lot 1 will be made into Parent B Lot 4001
- On ACAS 2022.4.3 the actual behavior is that the reparent check fails in the UI, and on the Roo layer there is a NullPointerException.
- This PR contains the fix for the NullPointerException. After that fix, we see the expected behavior.
- Tested in local …
> ACAS-600: Reparent lot behavior with maxAutoLotNumber

- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Start up a fresh instance of ACAS
- Bulk load some compounds
- Open up Bulk loader or CmpdReg
ACAS does not block you from registering compounds and requires a re-standardization
ACAS blocks you from registering compounds and requires re-standardization
- Bug was caused by the fact our auto-created initial standardizer history had no settings / settings hash
- Getting the applied settings and saving them in that initial history entry solves this issue
- Reproduced issue in k8s and in local dev (attached to remote bbchem)
- Confirmed on local dev (attached to remote bbchem) that this is fixed after the code changes
> ACAS-603: Fix standardization status on fresh system

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- Maintain transient multipleFragments property when finding an already register compound
- Don't do multiple fragment errors when finding an already registered parent
ACAS-601
Not tested yet
> ACAS-601: Fix for multiple calls to split service for already registered parents

- src/main/java/com/labsynch/labseer/api/ApiHealthController.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/Request.java
- Health endpoint queries all value types, which should be uniform on all systems of the same version. The idea is to have an endpoint tests the speed of querying the database which can be used to compare systems.
Curl example:
```
curl  "http://localhost:8080/acas/api/v1/health/checkDatabaseSpeed?testsToRun=100000&logData=False"
```
Output:
```
{"averageMsTime": 0.73629, "totalTime": 73629, "testsToRun": 100000, "logData": false}
```
ACAS-596
Ran curl and verified results with up to 1 million tests with log data False and True.
> ACAS-596: Health endpoint to check database speed.  Better logging of bbchem process and fingerprint requests

- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- Check for and delete standardization dry run compounds when deleting a bulk load file
ACAS-602
Ran standardization dry run
Purged a bulk load file and verified it was successful and that the rows associated with the parents were also deleted in standardization_dry_run table.
> ACAS-602 delete standardization dry run compounds when purging a bulk load file

- src/main/java/com/labsynch/labseer/api/ApiSaltController.java
- src/main/java/com/labsynch/labseer/service/SaltStructureService.java
- src/main/java/com/labsynch/labseer/service/SaltStructureServiceImpl.java
**Bug:** CmpdReg Salt Module: Different forms of same salt (e.g. charged & neutral) are being treated as duplicates
Steps to Reproduce:
- Log in to ACAS as CmpdReg admin >> Open CmpdReg Salts module
- Register a salt in it's neutral form (e.g. Dihydrogen Sulphate - H2SO4)
- Now register a charged form of the same salt (i.e. Sulphate ion - O4S-2)
- Provide different salt name & abbreviation for both entries
Previous Bug Results:
- The neutral form & charged form of same salt is getting treated as duplicates of each other
- CReg is generating '0' Compound ID for the later entry
Fixed Results:
- Both entries should get registered as different entries
- Both entries should receive unique Compound ID
Extra Information: 
- Added `saveStructureNoDupeCheck(salt)` in `saltStructureService` 
Logic …
> Salt Browser Bug: Charged and Uncharged Salts Being Treated as Duplicates 

- src/main/java/com/labsynch/labseer/chemclasses/CmpdRegMolecule.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureService.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegMoleculeBBChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/indigo/ChemStructureServiceIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/indigo/CmpdRegMoleculeIndigoImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/ChemStructureServiceJChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/CmpdRegMoleculeJChemImpl.java
- src/main/java/com/labsynch/labseer/db/migration/postgres/V2_0_7_1__Recalculate_exact_mass.java
- src/main/java/com/labsynch/labseer/domain/AbstractBBChemStructure.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- src/main/java/com/labsynch/labseer/service/RegSearchServiceImpl.java
- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
- src/main/java/com/labsynch/labseer/service/SaltStructureServiceImpl.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/LoadFullCompoundsUtil.java
- src/main/java/com/labsynch/labseer/utils/MoleculeUtil.java
**Steps to Reproduce:**
1. Be using an ACAS on k8s instance
2. Log in to ACAS as CmpdReg Admin
3. Open "CmpdReg Salts" module >> Click 'Create New Salt'
4. Draw a salt structure with '+' or '-' charges (e.g. sulphate) >> add Abbreviation & Name
5. Click on "Next"
6. Observe the Salt Charge & Salt Molecular Weight calculated on next page
**Expected Results:**
- The molecular weight is calculated for "charged" form of the salt & not the neutral one
- The "Salt Charge" is generated as per the drawn structure
**Previous Bug Results:**
- Molecular weight is generating for neutral form
- Salt charge is not computed (showing '0')
> k8s: CmpdReg Salts module is not calculating "charges" from salt's structure while registering salts 

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
In some instances, the standardizer actions will not recognize "false" as valid and will throw an error that 
`"NEUTRALIZE must have be a boolean value: false"`
This ultimately can lead to an error where `Request method 'POST' not supported` and appears to the user as a misleading `405` error. 
Setting this value directly as a bool value `false` will prevent this problem from happening. 
Note: This came up from this code introduced here: https://github.com/mcneilco/acas-roo-server/pull/423
> Replacing "false" with false when setting NEUTRALIZE config 

- src/main/java/com/labsynch/labseer/domain/SaltForm.java
- src/main/java/com/labsynch/labseer/service/SearchFormServiceImpl.java
Compound search via the corporate name uses the corporate prefix in the configuration to do matches. E.g
```
client.cmpdreg.serverSettings.corpPrefix=CMD
Available compounds: CMPD-0000001, MYCMPD-0000001
Search criteria: 1
Output: CMPD-0000001
```
Service attempts to do an actual match on `1` and `CMPD-0000001`. I have now updated the logic to only do matches on the unique identifier of the label and do matching based on `%id`.
[ACAS-598](https://jira.schrodinger.com/browse/ACAS-598)
I did some manual testing,
```
Available Compounds:
CMPD-0000001-001, CMPD-0000001-002, CMPD-0000002-001, ..., CMPD-0000010-001
MYCMPD-0000001-001
```
|Search Parameter|Matches                                                                               | …
> ACAS-598: Ignore corporate name prefix match in cmpdreg search.

- pom.xml
- src/main/java/com/labsynch/labseer/chemclasses/jchem/ChemStructureServiceJChemImpl.java
- src/main/java/com/labsynch/labseer/chemclasses/jchem/CmpdRegMoleculeJChemImpl.java
- src/main/java/com/labsynch/labseer/db/migration/postgres/jchem/R__Upgrade_Jchem_Tables.java
Provided JChem specific fixes to 2023.1.x  
Changed pom.xml to remove dependency on older commons.lang package.
Added JChem automigration every time JChem version changes.
> Pcheung/2023.1.x  j chem 22.22.0 upgrade  patched

- pom.xml
- https://github.com/mcneilco/acas-roo-server/pull/431 Removed org.apache.commons.lang3 this adds it back
- org.apache.commons.lang3 is used through out the code and is therefore a direct decency which should be included in the pom.xml
- It was removed because jchem itself in newer versions includes this dependency
None
- Performed a build with jchem
- Will let CI/CD tests run
> Add back org.apache.commons

- src/main/resources/db/migration/bbchem/postgres/V2.4.2.3__bbchem_structure_comment_field_expansion.sql
- Expands the bbchem structure comment fields to be of type text to accommodate for longer error messages and comments produced by bbchem service
ACAS-656
Reproduced the issue by:
- Loaded a structure into Creg
- Updated the structure to an invalid structure which produces a long error message
```
update lot set as_drawn_struct = '
Mrv2305 05012323552D          
0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 1 0 0 0 0
M  V30 BEGIN ATOM
M  V30 1 NHBoc -8.6265 2.645 0 0
M  V30 END ATOM
M  V30 END CTAB
M  END
`
```
- Ran CmpdReg standardization and verified CmpdReg standardization broke with `ERROR: value too long for type character varying(255)`
- Upgraded the system to version with this fix and verified CmpdReg standardization ran successfully and that the UI …
> ACAS-656: Expand comment fields of bbchem structure tables

- src/main/java/com/labsynch/labseer/api/ApiExperimentController.java
- src/main/java/com/labsynch/labseer/service/ExperimentService.java
- src/main/java/com/labsynch/labseer/service/ExperimentServiceImpl.java
- Implement filtering on projects for route /api/experiments/protocolCode name
ACAS-699
acasclient tests
> ACAS-699: Accept projects list to filter /api/experiments/protocolCodename/:code on from from nodejs

- src/main/java/com/labsynch/labseer/domain/SaltForm.java
- src/main/java/com/labsynch/labseer/dto/SearchFormReturnDTO.java
- src/main/java/com/labsynch/labseer/service/SearchFormServiceImpl.java
In the current Compound Registration search form, user has the option to specify "CPMD Number List". ACAS allows users to provide incomplete search terms e.g CMPD-0000004, 4, CMPD-004. It'll also return other results matching the `%X` & `%CMPD-XXX...` pattern. When returning results, we don't apply sorting on the results and it could be the case that CMPD-004 could be filtered out based on the maximum upper limit of results. 
We would here want to apply order, such that results that match the criteria the most are returned first in the results.
We have two steps in the workflow,
1. Get data sorted from the database.
2. Don't reorder database returned results.
In order to do the first step, we are using [pg_trgm.similarity](https://www.postgresql.org/docs/current/pgtrgm.html#id-1.11.7.44.6) …
> ACAS-674: Order corporate name based on similarity match.

- src/main/java/com/labsynch/labseer/domain/Lot.java
- src/main/java/com/labsynch/labseer/dto/LotDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ExportServiceImpl.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- Setters and gets with name `vendorID` instead of `vendorId`
- I believe this was all due to the change in 1.13.7 where we massively updated the roo dependencies (spring and hibernate) and removed roo.  The UI code has always sent and watched for "vendorID" but the roo services were now expecting "vendorId".
- I also verified that even with this bug, if you saved a lot via the user interface (sending `vendorID` instead of `vendorId`, this did not update the lot.vendorid field.  i.e. The UI was not deleting data.
https://jira.schrodinger.com/browse/ACAS-696
Ran acasclient tests. See new test https://github.com/mcneilco/acasclient/pull/144
Verified manually via the UI that vendorID is properly saved and shown in the UI.
> ACAS-696: Fix vendorID updates

- .github/workflows/trigger-tag.yml
- src/main/java/com/labsynch/labseer/domain/Lot.java
- src/main/java/com/labsynch/labseer/dto/LotDTO.java
- src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java
- src/main/java/com/labsynch/labseer/service/ExportServiceImpl.java
- src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
- src/main/java/com/labsynch/labseer/utils/MimeTypeUtil.java
This pull request was created by the upmerge workflow.
*tagged here because the api user for github actions owns the PR and cannot be a reviewer*
@bffrost
> ⬆️ Upmerge release/2023.2.x to release/2023.3.x

- src/main/java/com/labsynch/labseer/api/ApiDDictValueController.java
- src/main/java/com/labsynch/labseer/domain/DDictValue.java
- src/main/resources/db/migration/postgres/V2.4.2.2__ddict_value_label_text_search_index.sql
- Add code table/ddict value label text search which searches for label text and orders by a "best match"
- Add code table/ddict value short name match which finds the ddict value based on short name in the same route
- Added maxHits argument to limit results where the default is to not update.
- Added indexes on label_text to facilitate faster search including tsvector and a lower varcharops which was new to me and handles both lower case seraches and wildcard like search cases:
> The operator classes text_pattern_ops, varchar_pattern_ops, and bpchar_pattern_ops support B-tree indexes on the types text, varchar, and char respectively. The difference from the default operator classes is that the values are compared strictly character by character rather than according to the …
> ACAS-710: Code table label text search and short name match query parameters

- src/main/java/com/labsynch/labseer/dto/FileSaveSendDTO.java
To reproduce:
- Click View/Edit files
- Upload a new file to the list
- The UI automatically adds another file chooser below the new file uploaded. 
- Click the "cancel" button on this new file chooser line
- Click the "Upload" button
Expectation:
- The file I chose to upload is uploaded
Actual results:
- "error..." is displayed and the file is not uploaded.
Narrowed down the issue to this line in ```FileSaveSendDTO.java```:
```String writeup = writeupList.get(i);```
If the user inserted text (even a blank space) in writeup even if they hit "cancel" on the new file chooser line, there would be no issue BUT if they left the writeup field in the form blank and hit cancel, the writeupList would be blank and the code would fail on this line.
I'm guessing maybe there is some weird logic …
> Fix Bug: Hitting cancel on cmpdreg file upload widget new line causes "error..."

- .github/workflows/docker-image.yml
- .github/workflows/trigger-tag.yml
- Update Github Action to avoid deprecation warnings
ACAS-536
- `Trigger Dev Tag`
- Going to just merge the ACAS PR first and verify trigger-tag.yml works and then that should be good enough. 
- `Docker Image CI` 
- No warnings now: https://github.com/mcneilco/acas-roo-server/actions/runs/9422054525
- Before changes: https://github.com/mcneilco/acas-roo-server/actions/runs/9421219674
```
Annotations
52 warnings
acas-roo-server (indigo)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, docker/metadata-action@v3, docker/setup-qemu-action@v1, docker/setup-buildx-action@v1, docker/login-action@v1, docker/build-push-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16- …
```
> ACAS-536: Update Github Actions dependencies

- Dockerfile-multistage
- acas-roo-server is currently using version tomcat:9.0.62-jre11-openjdk-slim-buster which is subject to [NVD - CVE-2022-29885](https://nvd.nist.gov/vuln/detail/CVE-2022-29885).  Update to tomcat:9.0.97-jdk11-temurin-jammy which is the latest tomcat 9 version https://hub.docker.com/_/tomcat .  Also of note is that the slim-buster image is no longer available but this build works and seems to function properly so I went with it over the others which would have required more docker file build changes.
- I considered upgrading to latest tomcat [11.0.1](https://github.com/docker-library/tomcat/blob/37acdb35f2684d2c41e3c6ed96cc0403bec02447/11.0/jdk21/temurin-noble/Dockerfile) but decided against it for now
- Also added a few small fixes to fix legacy warning in docker builds:
```
- …
```
> ACAS-819: Update tomcat to 9.0.97

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemParentStructure.java
- src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemSaltFormStructure.java
- src/main/resources/db/migration/bbchem/postgres/V2.4.2.6__bbchem_remove_small_vs_bio_molecule_fingerprint_bit.sql
- Set substructure fields to be 2048 instead of 2112 (opposite of https://github.com/mcneilco/acas-roo-server/pull/438/files)
ACAS-831
- Started a 25-1 instance with the broken (larger bit column) and verified the same error when trying to register a structure or do a structure search (ERROR: bit string length 2048 does not match type bit(2112))
- Updated to this fixed version
- Verified the columns were all changed from 2112 to 2048.
- Registered a structure and verified substructure was also working.
- I didn't test the upgrade path where there were structures registered prior to the upgrade but I did truncate the bbchem_parent_structure table and restarted acas and verified the finger print was detected as missing and added back.
> ACAS-831: Remove extra bit for bio/small molecule flag

- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
The Salt editor was reporting MW changes when none were present. This was due to how Java handles Doubles, and comparing them with `!=` / `==` doesn't work well. Switched to `Double.compare` and tested.
- Tested editing a salt and not changing structure, and confirmed there's no warning shown
- Tested making a structure change to a salt and confirmed that there was a warning about MW change
> ACAS-843: Fix molWeight comparison when no changes are made

- Dockerfile-multistage
- Patch ACAS for CVE-2025-24813 by upgrading to tomcat:9.0.102
https://www.bleepingcomputer.com/news/security/critical-rce-flaw-in-apache-tomcat-actively-exploited-in-attacks/
> Apache recommended that all users upgrade to Tomcat versions 11.0.3+, 10.1.35+, or 9.0.99+, which are patched against CVE-2025-24813.
https://schrodinger.atlassian.net/browse/ACAS-845
None. Will let acasclient tests and QA catch issues.
> ACAS-845: Patch ACAS for CVE-2025-24813 by upgrading to tomcat:9.0.102

- src/main/java/com/labsynch/labseer/api/ApiStandardizationServicesController.java
- src/main/java/com/labsynch/labseer/service/StandardizationService.java
- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Remove call to failRunnningStandardization on start of tomcat for case when multiple replicas of ACAS are running and may be actually running standardization.
- Adds API route to fail any running standardization for case when process leaves standardization in running state but is killed.
https://schrodinger.atlassian.net/browse/ACAS-850
Started up acas and ran the following sql:
```
update standardization_history set dry_run_status = 'running';
update standardization_history set standardization_status = 'running';
```
Restarted ACAS and verified the status was still "running" to test that Roo was no longer automatically failing running standardizations.
```
acas=> select dry_run_status, standardization_status from standardization_history where dry_run_status = 'running' or …
```
> ACAS-850: Skip automatically failing running dry run or standardization on the start of roo

- src/main/java/com/labsynch/labseer/service/SaltServiceImpl.java
Ticket: [Renaming Salt Abbrev where Salt Abbrev is Appended to Lot Corp Name results in loss of reference to experiment/assay data](https://schrodinger.atlassian.net/browse/ACAS-853)
**Reproduction Steps**
1. For the given server the following should be set `ACAS_CLIENT_CMPDREG_SERVERSETTINGS_APPENDSALTCODETOLOTNAME: "true"`. Therefore the corp batch format should be `corp_batch_saltcode` 
2. Create a given salt 
3. Register compound with salt created in previous step (i.e. The lot corp name should look like `<Prefix>-000XXXX-<SaltAbbrev>`)
4. Register assay data using the lot corp name  
5. Go to the salt browser and edit the salt 
6. Only edit and change the Salt Abbrev 
7. There should be warnings like the following 
`The abbreviation of this salt will be changed`
`This salt is …
> ACAS-853: Renaming Salt Abbrev where Salt Abbrev is Appended to Lot Corp Name results in loss of reference to experiment/assay data 

- src/main/java/com/labsynch/labseer/service/SaltFormServiceImpl.java
**Previous Bug:** 
Changing the salt on a given lot with append salt code to corp name setting causes dissociation of assay data. The lot corp name is updated. However, the references to experiments, containers, etc. are lost. 
**Steps to Reproduce:** 
- For the given server the following should be set `ACAS_CLIENT_CMPDREG_SERVERSETTINGS_APPENDSALTCODETOLOTNAME: "true"` 
- Therefore the corp batch format should be `corp_batch_saltcode` 
- Create two salts 
- Register compound with one of the salts 
- Register assay data using the lot corp name  
- Go to the lot details page 
- Change the salt to the 2nd salt you created 
- Update the lot which renames the lot to  <Prefix>-000XXXX-NewSaltAbbrev
**Fix Results:** 
- Data associated with lot is modified to the new Lot Corp Name and …
> ACAS-856: Changing salts on lots with append salt code to corp name disassociates assay data 

- src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
- While working on ACAS-855 I realized that my recent PR to improve duplicate checking was updating all standardization dry run compounds to sync_status = READY.  This causes the actual standardization to run all compounds regardless of whether there structures actually changed.
- The fix for this is a one line change to the recent sql additions main in https://github.com/mcneilco/acas-roo-server/pull/480 to only update when the structure has actually changed.
ACAS-865
Ran the same tests as described in https://github.com/mcneilco/acas-roo-server/pull/480
Verified that the sync_status was only set to "READY" for changed structures
Verified that standardization only ran on synced structures.
> ACAS-865: Only set ready changed structures

- src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
- Fix for no UI response when multiple workers pick up dry run standardization
https://schrodinger.atlassian.net/browse/ACAS-867
- Ran dry run on an instance with 6 replicas to make sure this issue was reproducible.  Deployed the code and verified the UI consistently responded.
> ACAS-867: CmpdReg standardization may not respond when dry run is complete

- src/main/java/com/labsynch/labseer/api/ApiHealthController.java
- /health/live - Liveness probes check if the application is running and responsive; if the liveness probe fails, Kubernetes will restart the container.
- /health/ready - Readiness probes check if the application is ready to serve traffic (e.g., can connect to dependencies like databases); if the readiness probe fails, Kubernetes will temporarily remove the pod from service endpoints until it is.  We already had this as checkDatabaseSpeed?testsToRun=1 but this is a dedicated/simpler endpoint which does a similar check of the database connection.
- https://schrodinger.atlassian.net/browse/ACAS-876
- Verified that expected results of  acas/api/v1/live and acas/api/v1/ready both return `{"status":"UP"}` when a pod is up and healthy.
> ACAS-876: Add /health/live and health/ready endpoints for k8s

- src/main/resources/db/migration/postgres/V2.4.3.0__fix_p_api_analysis_group_results_agv2_ignored.sql
I encountered an issue when the `batch code` AGV is ignored, this API view will still display data against it. This was originally observed in LiveDesign and will be fixed there via DI mappings, but I thought it appropriate to also fix that same bug here.
I tested these changes indirectly by making the same change to LiveDesign Data Integrator mappings and confirmed they fixed the issue.
> ACAS-882: Replace p_api_analysis_group_results with fixes for agv2.ignored
