mcneilco/acas-roo-server

src/main/java/com/labsynch/labseer/api/ApiContainerStateController.java
src/main/java/com/labsynch/labseer/service/ContainerStateService.java
src/main/java/com/labsynch/labseer/service/ContainerStateServiceImpl.java

Added additional options to getContainerStatesByContainerValue route to match those on getContainerCodeNamesByContainerValue: like, rightLike, and maxResults. Similarly refactored query behavior to do a non-parameterized query for LIKE queries for better query plan optimization.

Sped up getContainerStatesByContainerValue and added options to match those on getContainerCodeNamesByContainerValue

---

pom.xml
src/main/resources/db/migration/postgres/V1.0.10.1__column_order_views.sql

Flyway migrations for api views to vend column order and condition info

---

src/main/java/com/labsynch/labseer/service/AuthorServiceImpl.java

Rewrote getUserProjects to properly include unrestricted projects

---

src/main/java/com/labsynch/labseer/domain/LabelSequence.java
src/main/java/com/labsynch/labseer/service/DataDictionaryServiceImpl.java

Signed-off-by: Brian Bolt <brian@mcneilco.com>

#139: label sequences should be truncated at 30 characters

---

src/main/java/com/labsynch/labseer/service/AuthorServiceImpl.java
src/main/java/com/labsynch/labseer/utils/PropertiesUtilService.java
src/main/java/com/labsynch/labseer/utils/PropertiesUtilServiceImpl.java
src/main/java/com/labsynch/labseer/web/ForgotPasswordController.java
src/main/java/com/labsynch/labseer/web/SignUpController.java
src/test/java/com/labsynch/labseer/utils/ReadPropsTest.java

See mcneilco/acas#710 for details.  Seperate pull request coming for the mcneilco/acas repo.

190 email from address

---

src/main/java/com/labsynch/labseer/service/LsThingServiceImpl.java

Only add label join if label predicates provided in the search criteria

747 advanced search interaction label predicates

---

src/main/java/com/labsynch/labseer/dto/LotDTO.java

Export SDF file from search returns ignored aliases

---

pom.xml

Reverts mcneilco/acas-roo-server#234

Revert "Switch to repo.spring.io"

---

src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
src/main/java/com/labsynch/labseer/chemclasses/indigo/ChemStructureServiceIndigoImpl.java
src/main/java/com/labsynch/labseer/chemclasses/jchem/ChemStructureServiceJChemImpl.java
src/main/java/com/labsynch/labseer/service/ChemStructureService.java
src/main/java/com/labsynch/labseer/service/MetalotServiceImpl.java
src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
src/main/java/com/labsynch/labseer/utils/PropertiesUtilService.java
src/main/java/com/labsynch/labseer/utils/PropertiesUtilServiceImpl.java
src/main/java/com/labsynch/labseer/utils/Request.java
src/main/java/com/labsynch/labseer/utils/Response.java

Added concurrent multi-threading calls to bbchem services to speed up standardization.  I also added the ability to save and search using cmpdregmolecules instead of just the mol structure string and because I added the ability to fetch a cmpdregmolecule (using its internal representation or impl) by cd_id, I greatly improved searches and standardization by using the already saved fingerprints.  
This brought about a 5x speed improvement in the overall process

ACAS-166-bb-concurrent

---

Dockerfile

Add openssl to the acas-roo-server images

---

src/main/java/com/labsynch/labseer/chemclasses/CmpdRegMolecule.java
src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureService.java
src/main/java/com/labsynch/labseer/chemclasses/bbchem/BBChemStructureServiceImpl.java
src/main/java/com/labsynch/labseer/chemclasses/bbchem/ChemStructureServiceBBChemImpl.java
src/main/java/com/labsynch/labseer/chemclasses/bbchem/CmpdRegMoleculeBBChemImpl.java
src/main/java/com/labsynch/labseer/domain/AbstractBBChemStructure.java
src/main/java/com/labsynch/labseer/domain/AbstractBBChemStructure_Roo_JavaBean.aj
src/main/java/com/labsynch/labseer/domain/AbstractBBChemStructure_Roo_Jpa_ActiveRecord.aj
src/main/java/com/labsynch/labseer/domain/StandardizationDryRunCompound.java
src/main/java/com/labsynch/labseer/domain/StandardizationDryRunCompound_Roo_JavaBean.aj
src/main/java/com/labsynch/labseer/domain/StandardizationDryRunCompound_Roo_Jpa_ActiveRecord.aj
src/main/java/com/labsynch/labseer/dto/StandardizationDryRunSearchDTO.java
src/main/java/com/labsynch/labseer/dto/StandardizationDryRunSearchDTO_Roo_JavaBean.aj
src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java
src/main/resources/db/migration/bbchem/postgres/V2.3.0.4__bbchem_structure.sql
src/main/resources/db/migration/postgres/V1.3.0.0__add_standardization_tables.sql

I cut a release/1.13.7 branch.

Fixes #253 Catch and save standardization and registration errors

---

Dockerfile
Dockerfile-bbchem
Dockerfile-indigo
Dockerfile-jchem
Dockerfile-multistage

Minor tomcat version bump
Fixes #303 
Ran acasclient tests

Bump tomcat to 9.0.68

---

Dockerfile
Dockerfile-bbchem
Dockerfile-indigo
Dockerfile-jchem
Dockerfile-multistage

Switching to 62

---

src/main/java/com/labsynch/labseer/domain/AbstractThing.java

Update experiment modified date when doing logical delete on experiment
ACAS-64
Ran acasclient tests added in : https://github.com/mcneilco/acasclient/pull/61

Set modified date when running logical delete of experiment

---

src/main/java/com/labsynch/labseer/api/ApiBulkLoadController.java

- Created a route that returns a list of lot corp names given a bulk file ID. 
- Tested and working when generating an updated SDF file or checking if the bulk file has been changed given its ID.

Added route to get lot corp names from bulk file ID

---

.github/workflows/DE-docker-image.yml
pom.xml

Dalejerikson deploy test

---

Dockerfile
Dockerfile-bbchem
Dockerfile-indigo
Dockerfile-jchem
Dockerfile-multistage

Reviewed the following checklist, validated presence of best practice, and made minor modifications. The build time and size of the image are reasonable. The longest steps are downloading dependencies/packages so caching these (whether locally, on GitHub, etc.) will significantly decrease time to build. The two changes I made to align with best practices are: 
- Replace ADD with COPY where applicable in order to prevent path traversal and zip slip vulnerabilities 
- Organize and sort package dependencies alphanumerically 
I experimented with moving RUN and ADD steps around. I wanted to move long running, infrequently changed steps to higher up in the file(s). However, this yielded insignificant improvements. I also tried minimizing the number of layers but that would increase the …

DE Docker Optimization 

---

src/main/java/com/labsynch/labseer/service/ParentSwapStructuresServiceImpl.java

Update `swapParentStructures` API to support parent aliases. If the API user passed a parent alias name instead of a corporate name to the `swapParentStructures` API it fails with the error,
```
"Caught error while fetching parent"
```
Goal here is to support unique parent aliases i.e if no parent is found matching the corporate name then fallback to finding if there is a unique parent alias matching the name. If a unique parent alias exists then use the parent as the object to swap structures.
Create a private API that handles the logic for returning the parent based on the criteria.
[ACAS-440](https://jira.schrodinger.com/browse/ACAS-440)
Added acasclient tests to check the behaviour.

Update swapParentStructures to support parent aliases.

---

src/main/resources/db/migration/postgres/V2.4.0.7__add_more_default_file_types.sql

- Adding a few more specific file types for analytical files
Tested locally and confirmed new options showed up in the UI:

ACAS-499: Add a few more default file types

---

pom.xml

Merged the 4 dependapot pom.xml upgrades into this branch, confirmed I can compile and acasclient tests pass.
Tested locally, and all acasclient tests passed.

ACAS-516: Merge dependabot PRs

---

Dockerfile
Dockerfile-bbchem
Dockerfile-indigo
Dockerfile-jchem
Dockerfile-multistage

- Upgrade to nodejs 18
ACAS-493
Ran acas client tests locally

ACAS-493: Upgrade to nodejs 18

---

src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java

- Run parallelStream when checking for duplicate structures
I saw the following improvements when running in K8s with 1CPU request and 3CPU limit
Before
```
populating standardization dry run table 100.0% complete (5000 of 5000) average speed (rows/min):4113.3643206778825
checking for standardization duplicates 100.0% complete (5000/5000) average speed (rows/min):6638.0549963498
```
After
```
populating standardization dry run table 80.0% complete (4000 of 5000) average speed (rows/min):4101.372250798913
checking for standardization duplicates 100.0% complete (5000/5000) average speed (rows/min):18230.755209915547
```
ACAS-596
Ran through standardization with 5000 compound set on K8s.  There were no duplicates on the system so that branch of the code was not tested with this change.

ACAS-596: Use parallelStream when running dupeCheckStandardizationStructuresBatch

---

Dockerfile
src/main/java/com/labsynch/labseer/dto/LotDTO.java

This pull request was created by the upmerge workflow.

⬆️ Upmerge release/1.13.4 to release/1.13.5

---

src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java

This pull request was created by the upmerge workflow.

⬆️ Upmerge release/1.13.5 to release/1.13.6

---

.github/workflows/trigger-tag.yml

Upmerge dev tagging fix to 2023.4.x

ACAS-716 fix dev tagging logic

---

src/main/java/com/labsynch/labseer/service/BulkLoadServiceImpl.java

- This fixes multiple issues related to uploading multiple lots to a parent (existing or new) that used a parent alias.
- 
**To reproduce**
Bulkload a compound with a parent alias
Bulkload 2 lots of the same compound in a file (with or without mapping parent alias)
**Expectation**
No error
**Actual outcome**
1 entries had: Within File, Parent Alias XXXXXX is not unique
**To reproduce**
Bulkload 2 lots of the same compound in a file (mapping parent alias)
**Expectation**
No error
**Actual outcome**
1 entries had: Within File, Parent Alias XXXXXX is not unique
ACAS-738
Changed acas default to enforce globally unique parent alias (https://github.com/mcneilco/acas/pull/1142) and wrote acasclient tests (https://github.com/mcneilco/acasclient/pull/154)

ACAS-738: Fix duplicate parent alias checks dry run

---

Dockerfile-multistage

See description and testing on the acas repository https://github.com/mcneilco/acas/pull/1155

ACAS-727: Update to nodejs 20 LTS

---

src/main/resources/db/migration/postgres/V2.4.2.5__file_value_encode_sql_function.sql

- Adds encode_file_value function which can be used to specifically encode file values which are in the format `experiments/EXPT-00000001/analysis/uploadedFiles/<file Name>`
- The sql itself details how this is done: https://github.com/mcneilco/acas-roo-server/pull/467/files#diff-f362c9cec12a5bd4e40de4a5eb0e0391acf6711050eb50b30bcbcb4fc5221fd8R14
- 
- ACAS-753
I used the following experiment loader file:
[ACAS_Results_#&%_ñÜ @?='"!$()*+,-.:;=_~.csv](https://github.com/user-attachments/files/15962582/ACAS_Results_._nU.%40.%2B.-._.csv)
Inline file value zip (which contains `Image_#&%_ñÜ @?='"!$()*+,-.;=_~.png`):
[Image_#&%_ñÜ @?='"!$()*+,-.;=_~.png.zip](https://github.com/user-attachments/files/15974218/Image_._nU.%40.%2B.-._.png.zip)
And Report file: `
[Image_#&%_ñÜ …

ACAS-753: Encode file values helper function

---

src/main/resources/db/migration/postgres/V2.4.2.6__user_session_table.sql

Reverts mcneilco/acas-roo-server#469

Revert "ACAS-828: User sessions table"

---

src/main/resources/db/migration/postgres/V2.4.2.6__user_session_table.sql

- Add table for user session management
ACAS-823
ACAS client tests

Revert "Revert "ACAS-828: User sessions table""

---

src/main/java/com/labsynch/labseer/api/ApiStandardizationServicesController.java
src/main/java/com/labsynch/labseer/service/StandardizationService.java
src/main/java/com/labsynch/labseer/service/StandardizationServiceImpl.java

This pull request was created by the upmerge workflow.
*tagged here because the api user for github actions owns the PR and cannot be a reviewer*
@bffrost

⬆️ Upmerge release/2025.2.x to master
